cc_library(
  name = "nnetworks",
  srcs = [
    "connection.cc",
    "end.cc",
    "feedforward.cc",
    "hopfield.cc",
    "method.cc",
    "node.cc",
  ],
  hdrs = [
    "feedforward.hh",
    "method.hh",
    "hopfield.hh",
    "neuralnetwork.hh",
    "node.hh",
  ],
  deps = [
    "//nalso/utils"
  ],
  visibility = ["//visibility:public"],
)
