cc_library(
  name = "parsers",
  srcs = [
    "alparser.cc",
    "splparser.cc"
  ],
  hdrs = [
    "alparser.hh",
    "splparser.hh"
    ],
  deps = [
    "//nalso/utils",
    "//nalso/logicstructs:logic",
    "@boost.spirit",
    ],
  visibility = ["//visibility:public"],
)
