cc_library(
  name = "algorithms",
  srcs = [
    "ablogprog.cc",
    "cilp.cc",
    # "hohopfield.cc",
  ],
  hdrs = [
    "ablogprog.hh",
    "cilp.hh",
    # "hohopfield.hh",
    "networkbuilder.hh",
    ],
  deps = [
    "//nalso/utils",
    "//nalso/logic",
    "//nalso/neural",
  ],
  visibility = ["//visibility:public"],
)
