cc_library(
  name = "algorithms",
  srcs = ["cilp.cc"],
  hdrs = [
    "cilp.hh",
    "networkbuilder.hh",
    ],
  deps = [
    "//nalso/utils",
    "//nalso/logic",
    "//nalso/networks:neural",
  ],
  visibility = ["//visibility:public"],
)
